### ISSUE TITLE
Comma separated vs tab separated files

### ISSUE THREAD

**Issue by thomasvangurp** [thomasvangurp/epiGBS#5]
Both demultiplex.py and demultiplexV2.0.py default to "barcodes.csv" as a default option; however, the code requires tab-delimited files, not comma-delimited.

**Comment by NielsWagemaker** [comment]
Be aware that from excell saving as tab delimited does not yet produces the correct file format (the end of line code has to be adjusted using vi.... What was the command within vi Thomas?

**Comment by NielsWagemaker** [comment]
i believe changing line 235 to :
file_in = open(barcodes, 'rU')
might also do the job...

**Comment by thomasvangurp** [comment]
I've just changed the relevant lines, I think it should work now.

**Comment by NielsWagemaker** [comment]
did you changed the demultiplex SGBS script? i don't see the changes you made? I think my problem still leads back to the initial barcode file.... see mail... sometimes additional fields are placed in the sam file ??? see mail for picture...
